In [1]:
catalog="tabfm_and_tsfm"
schema="marc_susagna_bronze"

In [2]:
%sql
SELECT * FROM tabfm_and_tsfm.marc_susagna_bronze.crm_bronze

DataFrame[lead_id: string, company: string, contact_name: string, opportunity_value: string, stage: string, created_date: string, _rescued_data: string, ingestion_timestamp: timestamp, source_file: string]

In [3]:
spark.sql("SELECT * FROM tabfm_and_tsfm.marc_susagna_bronze.crm_bronze")

DataFrame[lead_id: string, company: string, contact_name: string, opportunity_value: string, stage: string, created_date: string, _rescued_data: string, ingestion_timestamp: timestamp, source_file: string]

In [5]:
my_df = (
    spark.read.table(f"{catalog}.{schema}.crm_bronze")
    .select("lead_id", "company")
)

In [6]:
display(my_df)

DataFrame[lead_id: string, company: string]

In [7]:
new_silver_table = f"{catalog}.marc_susagna_silver.crm_silver_from_vscode_notebook"

(
    my_df.write
    .mode("overwrite")
    .saveAsTable(new_silver_table)
)